### ISSUE TITLE
Add ability to interpret flight category when its not present in the XML

### ISSUE THREAD

**Issue by lynndixon** [lynndixon/LiveSectional#22]
Currently, if the flight category is not present in the XML we just set the light color to white to indicate this.  Some stations will routinely NOT include the flight category, but DO include the ceilings and visiblity, which can be used to infer the category.  

**For example:**
On using Cloud bases:
LIFR is below 500 AGL 
IFR is between 500 and 1000 AGL
MVFR is between 1000 and 3000 AGL
VFR is above 3000 AGL

On using Visibility:
LIFR < 1 statute mile
IFR is between 1 and 3 statute miles
MVFR is between 3 and 5 statute miles

**Comment by lynndixon** [comment]
Currently working on this with some code given to me by a friend on slack named "ppf4life".  He has this working on his map, and has been gracious to give me the logic he is using.  I am working to incorporate this into my codebase in this branch:  https://github.com/lynndixon/LiveSectional/tree/feature-add-flight-category-interpretation

**Comment by pp4life** [comment]
Haha, don't have it quite working on my map just working in a test environment printing to the screen. My "map" is still a pile of NeoPixels and an RPi with a few buttons soldered directly to the I/O header.

**Comment by lynndixon** [comment]
@pp4life it worked great on my setup!  I added a logging line so I could determine if it was in the logic and determined the category and it did indeed!
